openapi: "3.0.2"
info:
  title: "Appili OpenSource APIs"
  description: "APIs documentation is fun. The below is CRUD API developed using AWS tools. Anyone can use this APIs in their project., Please contact me if you get errors with CORS issues."
  version: "2.5"
  termsOfService: ""
  contact:
    name:  "Appili Vamsi Krishna"
    url: "https://appili.dev"
    email: "appilivamsikrishna@gmail.com"
  license:
    name: "APACHE 2.0 "
    url: ""

servers:
- url: "https://appili.gives"

paths:
  /items:
    get:
      tags:
      - Fetch all items
      summary: "fetch all items from the database"
      description: "This API call fetches all items from the database"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'

components:
  schemas:
    "200":
      title: Successful response
      type: object
      properties:
        3h:
          type: number
          description: Snow volume for the last 3 hours
          example: 6
      